### PR TITLE
List the base gems expected in inventory slots

### PR DESCRIPTION
**Pull request by zr40**
This adds a list showing which base gems should be in which inventory slots for the selected recipe.

image

### CODE REVIEW

**Comment by 12345ieee** [comment]
While this might be a useful feature for a first time user I'd really not want my window to gain a +50% in size with virtually no extra information.

I could see it better if it was toggle-able (opt-in) and/or below the instructions panel.

Thank you for your interest in wGC.

**Comment by zr40** [comment]
Well, it would be useful for everyone, because the expected locations depend on which gem colors are used in the formula. If, for example, I'm replacing `y` with `g` in the formula, then generic ends up in 1C instead of 1A, and black and red shift up to 1A and 1B. Without the list, it's quite impossible to guess in which slots the application ends up expecting the base gems.

The window does indeed get 50% bigger, but is that really a problem? Most of the time the window would be in the background anyway.

**Comment by CooLTanG** [comment]
In my opinion, we could just improve the help file, to explicitly tell what gems to use per different combine methods.  Or else just add a small one line label that gets updated based the spec.

**Comment by CooLTanG** [comment]
I've added this feature to beta client, but as a 3 liner box underneath Instructions.  Thanks for your contribution.

**Pull request closed without merging**
