### PR TITLE
Automatic Button Pressing

### PR DESCRIPTION
**Pull request by CooLTanG**
-Autoload first pattern of the Specs, also it loads instructions &
presses combine, so all you need to do is press "9" on A1 gem

-Fixed Resolutions issues in window mode (I hope)

-Gave an example on the Help Form.

-Altered Combiner a little to hide info & reshow, and place gem back in
original spot

-Removed fullscreen in options since its not needed anymore

### CODE REVIEW

**Comment by 12345ieee** [comment]
Hi @CooLTanG , it's the first time I receive a Pull Request, let's see what you got.
Would be helpful for me if you could break it in 2-3 different commits with the changes to different parts in different commits.

* resolution is now 1088x612: THANKS, I forgot about that when adding Steam support, the difference from 900x600 was so tiny in height (less than a pixel/cell) that I never noticed.
I'd be very happy to keep compatibility with the web version, too, maybe a switch to change the resolution between the 2 versions.

* fancy handler for GC window: welcome to that, again, if no GC is detected, maybe fall down to the browser version?

* pressing key_dot : why not, but the help must be updated for that, may also consider to send a lone mouse click, to be sure the user has focus in place (at least 4 people reported problems for that)

* key_g : the guy who originally built the wGC said this method was slower, did you benchmark it?

* move gem to default: cool addition, approved

* auto load recipe: the 2 extra clicks were most for debugging and for the few folks that use wGC as a recipe parser, but faster flow is good, too

* closing form check: good addition

* spec description in help: great

I also add I can't test your changes now and will be busy IRL next 2-3 days, will check this out in the weekend.
I also have some more changes in a local branch, but seeing what you changed there'll be no merge conflicts, just be sure not to touch the debug logger.

Thank you for your interest in this project.

**Comment by CooLTanG** [comment]
First time for me doing a pull request too lol.

- But yeah I forgot about the flash version,  I'll make that compatible with it for sure. 
- I'll update the help with the pressing dot.
- The pressing G thing seems perfect to me, even running at a 20ms combine time.  It kinda ruins the pressing of it "12.8" isn't quite right I don't think with the modified resolution, but I can keep it in for the web version if people like


Thanks for the comments, I'll update it when I can with the changes, maybe a toggle for Steam/Flash or just get it to drop down to flash version if it can't find the steam version of it.




Date: Thu, 4 Jun 2015 02:03:29 -0700

**Comment by CooLTanG** [comment]
I've made those changes, although I'd love for you to look and test the "resolutionRatio" calculation for the steam version.  It works like 95% of the time for me, hard to find the problem with it, although its not very elegant of a calculation.

**Comment by CooLTanG** [comment]
Nevermind, I think I got the resolution working, the problem was caused by delay issues.  I'm a little lost there since at fullscreen, I can put it at 1ms delay and everything combines correctly (using killgem spec -> 987), but when I put it on 50ms delay it doesn't do it right.....

**Comment by 12345ieee** [comment]
Please, if you can, rebase the branch and resplit it in commits for every different feature/fix you implemented, the way it is now it makes very difficult to test changes singularly.

I have also uploaded the rc branch, with a couple extra changes, would you be so kind to rebase against that? I can do it myself, but splitting and rebasing your commits will be much more difficult for me than it is for you.

Thanks.

**Comment by CooLTanG** [comment]
I've never done any of that before, but I'll read up and give it a shot.

**Comment by 12345ieee** [comment]
Moved to #9.

**Pull request closed without merging**
